(function() {var implementors = {};
implementors["cbor"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"cbor/decoder/enum.DecodeError.html\" title=\"enum cbor::decoder::DecodeError\">DecodeError</a>",synthetic:false,types:["cbor::decoder::DecodeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.FromUtf8Error.html\" title=\"struct alloc::string::FromUtf8Error\">FromUtf8Error</a>&gt; for <a class=\"enum\" href=\"cbor/decoder/enum.DecodeError.html\" title=\"enum cbor::decoder::DecodeError\">DecodeError</a>",synthetic:false,types:["cbor::decoder::DecodeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/str/struct.Utf8Error.html\" title=\"struct core::str::Utf8Error\">Utf8Error</a>&gt; for <a class=\"enum\" href=\"cbor/decoder/enum.DecodeError.html\" title=\"enum cbor::decoder::DecodeError\">DecodeError</a>",synthetic:false,types:["cbor::decoder::DecodeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"cbor/slice/enum.ReadSliceError.html\" title=\"enum cbor::slice::ReadSliceError\">ReadSliceError</a>&gt; for <a class=\"enum\" href=\"cbor/decoder/enum.DecodeError.html\" title=\"enum cbor::decoder::DecodeError\">DecodeError</a>",synthetic:false,types:["cbor::decoder::DecodeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"cbor/encoder/enum.EncodeError.html\" title=\"enum cbor::encoder::EncodeError\">EncodeError</a>",synthetic:false,types:["cbor::encoder::EncodeError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
